version: "3.3"
services:
#
#  zipkin:
#    image: openzipkin/zipkin
#    container_name: zipkin
#    ports:
#      - "9411:9411"
#    networks:
#      - spring
#  rabbitmq:
#    image: rabbitmq:3.9.11-management-alpine
#    container_name: rabbitmq
#    ports:
#      - "5672:5672"
#      - "15672:15672"
#    networks:
#      - spring
#  eureka-server:
#    image: pylnevis/eureka-server:latest
#    container_name: eureka-server
#    ports:
#      - "8761:8761"
#    environment:
#      - SPRING_PROFILES_ACTIVE=docker
#    networks:
#      - spring
#    depends_on:
#      - zipkin

  postgres:
    container_name: customerdb
    image: postgres
    environment:
      POSTGRES_USER: customer
      POSTGRES_PASSWORD: customer
      PGDATA: /data/postgres
    volumes:
      - postgres-data:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - postgres
    restart: unless-stopped

  axonserver:
    image: axoniq/axonserver
    hostname: axonserver
    volumes:
      - axonserver-data:/data
      - axonserver-events:/eventdata
      - axonserver-config:/config:ro
    ports:
      - '8024:8024'
      - '8124:8124'
      - '8224:8224'
    networks:
      - axonserver

volumes:
  postgres-data:
  axonserver-data:
  axonserver-events:
  axonserver-config:

volumes:
  postgres-data:
    driver: local
    driver_opts:
      type: none
      device: ${PWD}/docker-data/postgres/data
      o: bind
  axonserver-data:
    driver: local
    driver_opts:
      type: none
      device: ${PWD}/docker-data/axon/data
      o: bind
  axonserver-events:
    driver: local
    driver_opts:
      type: none
      device: ${PWD}/docker-data/axon/events
      o: bind
  axonserver-config:
    driver: local
    driver_opts:
      type: none
      device: ${PWD}/docker-data/axon/config
      o: bind

networks:
  postgres:
    driver: bridge
  spring:
    driver: bridge
  axonserver:
    driver: bridge
