#version: "2.2"
#services:
#  postgres:
#    container_name: customerdb
#    image: postgres
#    environment:
#      POSTGRES_USER: customer
#      POSTGRES_PASSWORD: customer
#      PGDATA: /data/postgres
#    volumes:
#      - postgres:/data/postgres_destributed
#    ports:
#      - "5432:5432"
#    networks:
#      - postgres
#    restart: unless-stopped
#
#  zipkin:
#    image: openzipkin/zipkin
#    container_name: zipkin
#    ports:
#      - "9411:9411"
#    networks:
#      - spring
#  rabbitmq:
#    image: rabbitmq:3.9.11-management-alpine
#    container_name: rabbitmq
#    ports:
#      - "5672:5672"
#      - "15672:15672"
#    networks:
#      - spring
#  eureka-server:
#    image: pylnevis/eureka-server:latest
#    container_name: eureka-server
#    ports:
#      - "8761:8761"
#    environment:
#      - SPRING_PROFILES_ACTIVE=docker
#    networks:
#      - spring
#    depends_on:
#      - zipkin
#
#networks:
#  postgres:
#    driver: bridge
#  spring:
#    driver: bridge
#
#volumes:
#  postgres:
#  pgadmin: